# Generated by Django 2.2.9 on 2021-09-02 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='nome do produto', max_length=100, verbose_name='Nome do Produto')),
                ('categoria', models.CharField(help_text='Ex: frios, massas', max_length=200, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, help_text='R$', max_digits=8, verbose_name='Preço')),
                ('medida', models.CharField(help_text='Ex: kg, Un', max_length=2, verbose_name='Medida')),
                ('estoqueatual', models.IntegerField(verbose_name='Estoque Atual')),
                ('estoqueminimo', models.IntegerField(verbose_name='Estoque Minimo')),
                ('nomeempresa', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('situacaoestoque', models.CharField(help_text='Ex: Regular/Negativo', max_length=100, verbose_name='Situação do Estoque')),
            ],
            options={
                'unique_together': {('nome', 'nomeempresa')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('telefone', models.CharField(help_text='Digite o numero do Telefone', max_length=12, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Digite seu email', max_length=100, verbose_name='E-mail')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
            ],
            options={
                'unique_together': {('empresa', 'cnpj', 'telefone', 'email')},
            },
        ),
        migrations.CreateModel(
            name='RepresentanteComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('nomecontato', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='nomecontato', to='core.Fornecedor')),
            ],
            options={
                'unique_together': {('nomecontato', 'endereco', 'cpf')},
            },
        ),
    ]
