# Generated by Django 2.2.9 on 2021-09-02 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('daa32ab7-6858-4239-860a-94005b8440de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
