# Generated by Django 2.2.9 on 2021-09-02 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210902_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52f901a5-8716-43bc-af39-d2e435dbd49e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
