# Generated by Django 2.2.9 on 2021-09-02 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210902_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97b7321a-41bb-43d1-bf68-1c347e790659'), editable=False, primary_key=True, serialize=False),
        ),
    ]
