# Generated by Django 2.2.9 on 2021-09-02 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210902_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantecomercial',
            name='empresa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8daf256-e1d7-4e5f-afb1-fc09739cb9df'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='representantecomercial',
            name='nomecontato',
            field=models.CharField(max_length=100, verbose_name='Nome do Representante'),
        ),
    ]
