# Generated by Django 2.2.9 on 2021-09-02 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210902_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa6015bf-4ee1-4b16-8360-d0cf8503e175'), editable=False, primary_key=True, serialize=False),
        ),
    ]
