# Generated by Django 2.2.9 on 2021-09-02 03:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210902_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20b83992-67c7-42c2-a591-bf8ce387b282'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='representantecomercial',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
