# Generated by Django 2.2.9 on 2021-09-02 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210902_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6333105-dd68-4e22-826a-7746fc3d7e4c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
