# Generated by Django 2.2.9 on 2021-09-02 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210902_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ca39a7d-eda9-4f9e-85ca-0c56fa52cc0f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
