# Generated by Django 2.2.9 on 2021-09-02 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210902_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representantecomercial',
            options={'verbose_name_plural': 'Representantes Comerciais'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d96307f3-a061-4853-b96e-1ad16e4bece4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
